### ISSUE TITLE
Inbox issues

### ISSUE THREAD

**Issue by daipol50** [rnwood/smtp4dev#1025]
My messages keep going to spam I need help to promote my business my messages keeps going to spam I need help please🙏🙏🙏

**Comment by f3** [comment]
❓
This project is not seem to be for production use...
First line of the [readme](https://github.com/rnwood/smtp4dev#readme) says:

> smtp4dev - the fake SMTP email server for development and testing.

**Comment by jafin** [comment]
Hi @daipol50 , This project is for **testing** SMTP services in a dev environment. If you are using it as a real mail server, I would advise you to look for alternatives. Even though this app has forwarding capabilities, etc it is not purposed as a production mail server.
