### ISSUE TITLE
[Feature] Stop Chrome updates on Azure Pipelines from breaking the build every few months

### ISSUE THREAD

**Issue by rnwood** [rnwood/smtp4dev#1065]
Whenever Chrome is updated, the build is broken because of a static dependency on Chromedriver. The version of this must match the version of Chrome where the test runs. 

It looks like this package can make the dependency on Chromedriver dynamic:
https://www.nuget.org/packages/WebDriverManager/

**Comment by jafin** [comment]
more resilient builds sounds positive!
