### ISSUE TITLE
[Feature] Switch to view plain text preview of message

### ISSUE THREAD

**Issue by targzeta** [rnwood/smtp4dev#1079]
Is there a option to see the text/plain part of a multipart/alternative MIME? If a have a mail as text/plain and text/html, only the HTML part is rendered.

Thank you in advance,
Emanuele

**Comment by rnwood** [comment]
Not directly in the message preview. However you can switch to the "Parts" tab and it's visible there with some navigation.

Leaving this open to add this feature directly in message preview.

**Comment by targzeta** [comment]
Thank you!

Emanuele

**Comment by rnwood** [comment]
This feature has been implemented in the above PR and will be available in the latest pre-release builds. Note that it will only display if the message has a plain text body/alternative. I have chosen not implement any plain text conversion from HTML.
