### ISSUE TITLE
[Feature] Add Configuration to Disable Settings Gear

### ISSUE THREAD

**Issue by bgaisford-om** [rnwood/smtp4dev#1096]
Would it be possible to add a configuration setting that would disable (and or hide) the Settings gear functionality in the upper right corner?  Thanks in advance for your consideration.

**Comment by rnwood** [comment]
Thanks for the suggestion. This is a great idea.

**Comment by rnwood** [comment]
Implemented as command line option `--locksettings` or appsettings.json `ServerSettings\LockSettings`. 
Docs have been updated: https://github.com/rnwood/smtp4dev/wiki/Configuration

Will be available in the CI build once merged.

**Comment by rnwood** [comment]
This has now been merged. Available in the latest CI releases.

**Comment by bgaisford-om** [comment]
Thank you sir!
