### ISSUE TITLE
Include the latest version of SQLitePCLRaw.lib.e_sqlite3 to fix osx-arm64

### ISSUE THREAD

**Issue by LennardF1989** [rnwood/smtp4dev#1101]
Now that you've upgraded to .NET 6, I had a change to test M1 support. Initially this didn't work because the osx-arm64 runtime is not included by default.

After running `dotnet publish -r osx-arm64 --self-contained -c Release` I had a version to test.

First issue was pretty much this: https://github.com/Jackett/Jackett/issues/5589

I fixed it by running `sudo xattr -r -d com.apple.quarantine .` inside the smtp4dev folder.

Next was the fact that the e_sqlite3.dylib was missing. Apparantly, this was not added before v.2.0.5 of the library included by EF Core SQlite: https://github.com/ericsink/SQLitePCL.raw/issues/375

So by manually including SQLitePCLRaw.lib.e_sqlite3 2.0.5 or newer (I tested 2.1.0) as a dependency, I effectively overwrite the older version shipped by EF Core SQLite.

Doing another publish then properly builds a working version for OSX' powered by M1 chips!

**Comment by rnwood** [comment]
Closing as believe this should be resolved (although have no Mac to test on). Feel free to reopen.
