### ISSUE TITLE
Clear all button sometimes doesn't do anything

### ISSUE THREAD

**Issue by redtopia** [rnwood/smtp4dev#1166]
The [X] button in both the email list and the session list sometimes doesn't delete anything and provides no indication that anything failed. Another click will then delete all items.

**Comment by rnwood** [comment]
On the client side, errors are handled and displayed, so I'm not sure what's happening here if nothing is being displayed. For anyone that can reproduce this, please can you post any output you see in the smtp4dev console; is there an error there?

**Comment by rnwood** [comment]
Closing this stale issue. Please comment if you can still reproduce this with the latest versions and I will reopen.
