### ISSUE TITLE
Example in appsettings.json does not agree with the code

### ISSUE THREAD

**Issue by TooMuchBlue** [rnwood/smtp4dev#1170]
[The latest appsettings.json](https://github.com/rnwood/smtp4dev/blob/master/Rnwood.Smtp4dev/appsettings.json) file in master is showing incorrect information about ServerOptions->TlsMode

> // Specifies the TLS mode to use. Valid options are: None, Auto or StartTls.
    // Default value: "None"
    "TlsMode": "None",

The actual allowed values are None, StartTls, ImplicitTls, defined in /Server/TlsMode.cs

I think maybe this comment was meant for RelayOptions -> TlsMode, which is defined by Mailkit.Security.SecureSocketOptions to allow None, Auto, SslOnConnect, StartTls, StartTlsWhenAvailable

> // Sets the TLS mode when connecting to relay SMTP server
    // See: http://www.mimekit.net/docs/html/T_MailKit_Security_SecureSocketOptions.htm
    // Default value: Auto
    "TlsMode": "Auto",

This caused me confusion while trying to diagnose other problems, and it will probably confuse others.

**Comment by rnwood** [comment]
Thanks for spotting this.
