### ISSUE TITLE
Anti-Virus False Positive - Maybe?

### ISSUE THREAD

**Issue by Dulux-Oz** [rnwood/smtp4dev#1190]
Just ran smpt4dev.exe for the first time (the latest release version - v3.1.4) and Avast Free Antivirus said it was infected.

I assume that this is a False Positive, and I'm letting you know that this is the case.

Cheers

Dulux-Oz

**Comment by jafin** [comment]
@Dulux-Oz , can you check on virus-total? I suspect false-positive.
I wasn't sure which binary your AV alerted to, but I uploaded v3.1.4 winx64 and here are the results https://www.virustotal.com/gui/file/2285ed3a7bab30d02195b99761637fe55006c088202315ad68cf387aa83734b2

`No security vendors and no sandboxes flagged this file as malicious`

If you did have any concerns, you could always build from source too.
