### ISSUE TITLE
ui issues not reflecting server logs of messages received

### ISSUE THREAD

**Issue by leblancmeneses** [rnwood/smtp4dev#1193]
docker image: rnwood/smtp4dev:3.2.0-ci20220905102

![smtp4dev](https://user-images.githubusercontent.com/730804/194787864-77397a30-80cd-4f0d-9923-1f729f9164de.png)

---
pod with no volume for /smtp4dev
I sent three emails and only saw the first. 
Sessions tab doesn't show anything.

---
pod with with volume for /smtp4dev to persist emails
I sent multiple emails and only saw 1. I took a break and when I came back I saw emails in the dashboard.
I saw lots of sessions but was unable to clear.

Nice project by the way!

**Comment by rnwood** [comment]
Thanks for reporting. 

If you are still experiencing this, please can you check for any errors in the browser console.
