### ISSUE TITLE
Is there a way to connect to the local smtp4dev instance programatically via IMAP ?

### ISSUE THREAD

**Issue by jprealini** [rnwood/smtp4dev#1209]
Hi!

I know this is not a bug, but had no idea where to ask this question.

I am trying to use a containerized instance of smtp4dev for email testing from Cypress. Is there a way to use a javascript/node imap client to connect to the running smtp4dev service and fetch emails (I guess via IMAP) ? 
I built a similar implementation using Ethereal and connecting to it using a package called IMAPFLOW, but can't seem to find an imap client that will allow me to connect to smtp4dev like that

THanks!

**Comment by usersina** [comment]
I do something similar but with java sort of like this
```java
// The "smtp" session
Session session = Session.getInstance(getProperties());

// The actual store that uses IMAP
store = session.getStore("imap");
store.connect("localhost", "", "");

// An instance to the inbox, searching is also possible
emailInbox = store.getFolder("INBOX");
emailInbox.open(Folder.READ_WRITE);
```

I have a more complete example in [this issue](https://github.com/rnwood/smtp4dev/issues/1244#issue-1577776816).
