### ISSUE TITLE
Group notifications when there is more than 1 email

### ISSUE THREAD

**Issue by redtopia** [rnwood/smtp4dev#121]
Instead of issuing a single notification for each email, issue a single notification for one or more emails when possible.

There are times in my development when hundreds of email are generated, after which I have to turn off notifications for smtp4dev, which takes extra clicks/time, and I generally want to see notifications for smtp4dev, so I will have to turn it back on at some point. I would be fine seeing a single notification anytime smtp4dev knows there is one or more emails.

**Comment by redtopia** [comment]
I am running the latest pre-release and noticing that this issue has not been addressed. I'm interested to know if this is on the roadmap. I'm getting hammered with windows notifications on Win10. I don't want to turn them off, and I don't want to get 1000 of them. Is there a OS workaround, or some other way to deal with this?

**Comment by rnwood** [comment]
Experimenting with this in #145

**Comment by rnwood** [comment]
This has been implemented.
