### ISSUE TITLE
Mac OS docker - not working

### ISSUE THREAD

**Issue by redtopia** [rnwood/smtp4dev#1210]
I'm trying to get smtp4dev working on Mac OS with Docker. I followed the docker install instructions by running this command:

    docker run --rm -it -p 3000:80 -p 2525:25 rnwood/smtp4dev

and am able to create and run the container. However, I cannot access the web interface. Any suggestions?

**Comment by JakobStadlhuber** [comment]
Have you tried `-p 25:25` instead of `-p 2525:25 `

**Comment by trodix** [comment]
Same issue here. I tried with ports 25:25 / 1025:25, same thing, there is a issue with the port 25 of the container.

![image](https://user-images.githubusercontent.com/34584317/210136141-b0fda6ff-78ce-404b-9416-f88860045a2e.png)

![image](https://user-images.githubusercontent.com/34584317/210136303-457bb22f-a7ce-402e-8d3f-e533145d5c53.png)

![image](https://user-images.githubusercontent.com/34584317/210136154-e77d2897-6be9-4845-b4a4-682a7d81bdaf.png)

![image](https://user-images.githubusercontent.com/34584317/210136186-fe7c4490-2a7f-4439-907b-340ab84980b8.png)

**Comment by kshkaran2k** [comment]
> I'm trying to get smtp4dev working on Mac OS with Docker. I followed the docker install instructions by running this command:
> 
> ```
> docker run --rm -it -p 3000:80 -p 2525:25 rnwood/smtp4dev
> ```
> 
> and am able to create and run the container. However, I cannot access the web interface. Any suggestions?

Hi,

I am able to access the web UI on port 3000 as mentioned in the command. To send email, it was not connecting. So changed the `2525:25` to `25:25`.

**Comment by kshkaran2k** [comment]
Thanks. I will try it
