### ISSUE TITLE
mail with DSN parameter RET in MAIL FROM: causes 501 error

### ISSUE THREAD

**Issue by nlppp1** [rnwood/smtp4dev#1212]
On Windows 3.1.4

220 TEST smtp4dev ready
EHLO domain.com
250-Nice to meet you.
250-8BITMIME
250-SIZE
250-SMTPUTF8
250-AUTH=CRAM-MD5 PLAIN LOGIN ANONYMOUS
250 AUTH CRAM-MD5 PLAIN LOGIN ANONYMOUS
MAIL FROM:<a@domain.com> RET=HDRS
501 Parameter RET is not recognised
QUIT
221 Goodbye

Thanks

**Comment by rnwood** [comment]
Thanks for reporting this. Currently the server does not support the DSN extension. The DSN extension is not listed in the EHLO response and so the client should not be sending the RET parameter.

This is covered here
https://datatracker.ietf.org/doc/html/rfc3461#section-3

What SMTP client/library are you using here?

**Comment by nlppp1** [comment]
Thanks for the response, much appreciated. It's a 3rd party line of business app so I'm not sure what library they're using. I'll go back to them.
