### ISSUE TITLE
Public instance on Windows

### ISSUE THREAD

**Issue by savornicesei** [rnwood/smtp4dev#1235]
Hi all,
I've been looking at the documentation and IIS-related issue and it's still not clear for me how it should be configured on a win box to be accesible from other machine.

Do I need to set it up as a service for the mail server part, and in IIS for the web GUI part? I doubt the mail server can run in IIS.

Thank you.

**Comment by jafin** [comment]
@savornicesei , for IIS the web port is exposed bound to IIS, then a background process is started attached to the SMTP ports specified in config.  If there are no firewalls on the machine blocking inbound/outbound connections on those ports it should be accessible from another machine.

**Comment by savornicesei** [comment]
Ahh! It makes sense. Thank you.
