### ISSUE TITLE
Feature: Authentication for the web interface

### ISSUE THREAD

**Issue by FrankBWalsh** [rnwood/smtp4dev#1256]
Not really an issue per-say but would be great to have the email web message display server protected by a password that could be set in the config or on the startup.

Use case is that you might have this run on a server where you wanted to use it as a dummy email box if the software didn't have a feature that let you disable the email feature for account registration/activation links. 

Thanks!

**Comment by rnwood** [comment]
Implemented in PR #1419. This is off by default. See 'WebAuthenticationRequired' setting/option. It has been added to the settings dialog too.
