### ISSUE TITLE
Hello image doen'st work

### ISSUE THREAD

**Issue by ddiawara** [rnwood/smtp4dev#1259]
![image](https://github.com/rnwood/smtp4dev/assets/62718811/2246eb99-23ae-4f20-9c8a-b14ffdf00a3c)

![image](https://github.com/rnwood/smtp4dev/assets/62718811/2e599b0d-b4ee-4a6d-9c2d-6ffadf1f634d)

**Comment by rnwood** [comment]
This is not reproducable with the latest version.
