### ISSUE TITLE
Feature: Reply to an email

### ISSUE THREAD

**Issue by gillg** [rnwood/smtp4dev#1260]
Hello,

Because smtp4dev is awsome and almost complete for a end-to-end email workflow, that would be great to have a **reply** (not forward, not new email) feature from the web mailbox.
That should ceate a new email based on the body of the one you reply + propose to fill some custom text as response.

* The `To` header should be equal to `Reply-To` (if defined) else `From`.
* The `From` header should be cloned an prefixed with `Re: `
* `Message-Id` => `<{{random id}]@smtp4dev.local>`
* `References` => Stack the previous message ID `{{original Reference header if exists}} {{original message ID header}}`
* `In-Reply-To` => if was existing in the original email clone that header to the new email

Once the message is ready, the user clic on "send localy" and the message is just routed to the local SMTP server.

This enhancement allows to test workflows based on IMAP parsing like:
1. Your application send a notification to an end user
2. The end user "reply" to the message
3. Your application parse a mailbox to re-map the mails answers to its internal database.
This workflow is very common in helpdesk / ticketing systems.

Because the mailbox is shared for end-user and application mails, the application parsing IMAP should just filter on the `Message-Id != *@{{well kown domain}}`

**Comment by rnwood** [comment]
This is a great idea and I understand how this is useful for development. Open to PRs for this one if anyone is interested.

**Comment by rnwood** [comment]
Implemented in PR #1472.
