### ISSUE TITLE
Is there an in-memory persistence option

### ISSUE THREAD

**Issue by diegosasw** [rnwood/smtp4dev#1261]
I am using the docker image.

Is there any option to make persistence ephimeral or in-memory storage or similar?

Basically, I'd like to have it as part of a docker compose, but delete all its container's volume data when stopping docker compose

**Comment by rnwood** [comment]
Yes. `--db=` command line option (with no value) will use in memory DB.

See https://github.com/rnwood/smtp4dev/wiki/Configuration#command-line-options for more details
