### ISSUE TITLE
[Feature] Desktop edition - Minimize to tray

### ISSUE THREAD

**Issue by simon-spier0** [rnwood/smtp4dev#1263]
When I close the app window, it is closed, not minimized to system tray.
Can you please add possibility to minimize the new version 3 to system tray? I cannot find the option in settings. 

Thanks.

**Comment by rnwood** [comment]
I definately support re-introducing this version into v3. The Desktop version now has about 50% of the downloads for Windows platform.

PRs welcome.

**Comment by rnwood** [comment]
Suitable library?
https://github.com/HavenDV/H.NotifyIcon
