### ISSUE TITLE
DotNet (Nuget) security updates available

### ISSUE THREAD

**Issue by PDunbarCGI** [rnwood/smtp4dev#1264]
When scanning this application for vulnerabilities, I found that the following security updates are available for dependencies in smtp4dev.
--
DotNet (Nuget) Security Update for   Newtonsoft.Json (GHSA-5crp-9r3c-p9vr)
DotNet (Nuget) Security Update for   System.Net.Http (GHSA-7jgj-8wvc-jh57)
DotNet (Nuget) Security Update for   System.Text.Encodings.Web (GHSA-ghhp-997w-qr28)
DotNet (Nuget) Security Update for   Microsoft.AspNetCore.All (GHSA-6px8-22w5-w334)
DotNet (Nuget) Security Update for   Microsoft.Build.NuGetSdkResolver (GHSA-6qmf-mmc7-6c2p)
DotNet (Nuget) Security Update for   Microsoft.AspNet.Identity.Owin (GHSA-25c8-p796-jg6r)
DotNet (Nuget) Security Update for   System.Text.RegularExpressions (GHSA-cmhx-cq75-c4mj)
DotNet (Nuget) Security Update for   System.Linq.Dynamic.Core (GHSA-w65q-jcmv-28gj)

**Comment by rnwood** [comment]
Thanks for reporting. The project uses dependabot to keep moving forwards with dependency versions, but unfortunately the CI build it's reliant on has stopped working. I will be looking into this.

**Comment by rnwood** [comment]
This has been resolved.
