### ISSUE TITLE
[Bug] smtp4dev fails to receive mails after some time in IIS

### ISSUE THREAD

**Issue by rotsch** [rnwood/smtp4dev#1266]
After a few days of running in the background it seems that smpt4dev cannot receive mails anymore. A fix for this is to call the frontend in the browser after which mails are being received again.
This happens both when it's hosted as a service or in IIS in a Windows environment.
Is this known and is there a solution to this?

**Comment by rnwood** [comment]
Thanks for reporting this. Need to look into any timeouts and if the SMTP server etc needs to have it's lifecycle managed by the web app host so it's aware something is still running.

**Comment by rnwood** [comment]
For Windows Service, I hope that the PR #1291 should resolve this.

For IIS, please also use a version after this PR is merged and see the updated install/config instructions for IIS:
https://github.com/rnwood/smtp4dev/wiki/Installation#how-to-run-smtp4dev-as-a-windows-service

I will leave this ticket open for feedback. If you continue to experience this idle timeout, please can you post logs.

**Comment by rnwood** [comment]
Closing now. Please comment if you are still experiencing this issue after the latest versions.
