### ISSUE TITLE
Occasionally connections are answered with no greeting

### ISSUE THREAD

**Issue by groner** [rnwood/smtp4dev#129]
I've noticed a couple times today that a connection will open and get stuck.  My web application worker eventually times out and disconnects after 60s.

I ran wireshark to see where things are getting hung up, here's what I found:
<img width="1622" alt="Screen Shot 2019-05-07 at 6 52 31 PM" src="https://user-images.githubusercontent.com/47317/57337959-86aa8300-70f9-11e9-937c-484f9037df55.png">

This screenshot shows two connections, identified as 4 and 5 in the stream index column.  The time column contains seconds since the capture started.
- at 946 stream 4 begins
- at 1006 stream 4 is shutdown by the client in one direction only, no traffic has appeared
- at 1214 stream 5 begins
- at 1214 stream 4 smtp greeting appears, followed by a reset packet

I am using the linux docker image, with logs reporting "smtp4dev version 3.1.0-ci0552".  The host is lightly loaded, and all traffic is local.

**Comment by rnwood** [comment]
This should now be resolved. I was able to reproduce finally and consistently during work on #121.
