### ISSUE TITLE
Feature: Button in top to export emails

### ISSUE THREAD

**Issue by marvelbark2** [rnwood/smtp4dev#1350]
The tool is so good to test systems that send emails and something using only the ui to analyse the email received is so hard it will be great if it's possible to export them in csv or json

**Comment by rnwood** [comment]
What info would you want in the JSON or CSV?

________________________________
From: Masaoudi youness ***@***.***>
Sent: Tuesday, March 19, 2024 3:47:40 PM
To: rnwood/smtp4dev ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rnwood/smtp4dev] Feature: Button in top to export emails (Issue #1350)


The tool is so good to test systems that send emails and something using only the ui to analyse the email received is so hard it will be great if it's possible to export them in csv or json

**Comment by marvelbark2** [comment]
No matter, even json or csv at least exportable just to do more debugging and analysing

**Comment by rnwood** [comment]
Closing this one in favour of #1239.
