### ISSUE TITLE
[Bug] Plain text body view is showing HTML

### ISSUE THREAD

**Issue by iperezatloffa** [rnwood/smtp4dev#1372]
https://github.com/rnwood/smtp4dev/blob/bc7f6fbcf01ab206380d71b7a0a2474c5f12331d/Rnwood.Smtp4dev/Controllers/MessagesController.cs#L154

**Comment by rnwood** [comment]
Thanks for reporting. This is resolved with PR #1374

**Comment by iperezatloffa** [comment]
nice! Thank you!
