### ISSUE TITLE
[Feature] IPv6 support

### ISSUE THREAD

**Issue by josephsallan** [rnwood/smtp4dev#1400]
Currently smtp4dev listens only on IPv4. Would it be possible to enable IPv6 support?

Possibly either dual stack by default and/or configurable between:
- Dual stack
- IPv4 only
- IPv6 only

Very much appreciate all your work on this excellent tool!

**Comment by rnwood** [comment]
Implemented in PR #1408.

Dual stack is on by default. See appsettings "disableipv6"
