### ISSUE TITLE
Migration from sqlite to MySQL...

### ISSUE THREAD

**Issue by mueezmamoon** [rnwood/smtp4dev#1526]
Is there a way where we can use MySQL instead of the default sqlite database...

Let's say I want to deploy this application to AWS ECS, there isn't any way I can store the emails on sqlite!

Can someone help me out how I can configure the application to use MySQL.! Thanks!

**Comment by rnwood** [comment]
Only Sqlite is supported.

It should be possible to put the DB file into Amazon Elastic File system.

https://sqlite.org/forum/forumpost/8e84712c9d
