### ISSUE TITLE
Cannot send mails via API

### ISSUE THREAD

**Issue by dirk-olmes** [rnwood/smtp4dev#1527]
I'm trying to send eMails through the API using POST /api/Messages/send.  

The problematic part seems to be the message body: it's supposed to come in application/json but the schema type is only "string". So just sending a plain string results in an error: 
```
curl --request POST \
  --url 'http://localhost:15088/api/Messages/send?to=foo%40test.com&from=bar%40test.com&deliverToAll=false' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data 'this is a test mail'
  ```
results in:
```
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "$": [
      "'this is a test mail' is an invalid JSON literal. Expected the literal 'true'. Path: $ | LineNumber: 0 | BytePositionInLine: 1."
    ]
  },
  "traceId": "00-8abb21f1644d7fce226010786f0b79d4-8b9027932d846c5f-00"
}
```
Sending the body as text/plain gives the same error.

If I'm providing (potentially bogus) JSON in the body e.g. `{ "content": "this is a test mail"}` I'm getting `"The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1."`

Am I missing something really stupid or is this a bug in the API?

**Comment by rnwood** [comment]
Thanks for reporting this issue. This is an error in the documentation for the api (and also missing general documention for this action). This action needs a HTML request body using `text/html` content type.

**Comment by rnwood** [comment]
The API docs have now been corrected.
