### ISSUE TITLE
Unable to run in IIS

### ISSUE THREAD

**Issue by AaronSadlerUK** [rnwood/smtp4dev#1528]
I have followed the installation instructions for IIS, I have dot net 6,7 and 8 installed, however I get the following error:

`Application 'E:\HostingSpaces\smtp4dev\' failed to start. Exception message:
The app couldn't be found at E:\HostingSpaces\smtp4dev\.\Rnwood.Smtp4dev.dll. Confirm the app's main DLL is present. Single-file deployments are not supported in IIS.`

I have checked the the DLL is not included in the zip, is this a missing file or has a step not been documented?

**Comment by dieggoesteban** [comment]
Hey, did you find a solution? I'm struggling with the same problem. Thanks!

**Comment by AaronSadlerUK** [comment]
I used the noruntime version and that worked great

**Comment by rnwood** [comment]
Thanks for reporting. Wiki has been updated to correct this, which has been impacted by the change to use single file deployment.
