### ISSUE TITLE
Typo in Wiki should be 'Smtp4dev' instead of 'Smtpdev', I couldn't edit the Wiki so here goes..

### ISSUE THREAD

**Issue by rosdi** [rnwood/smtp4dev#1531]
On this page: `https://github.com/rnwood/smtp4dev/wiki/Installation`, there is typo, it should be Rnwood.Smtp**4**dev.dll and not `Rnwood.Smtpdev.dll`

----------------------

Correct: '... and you should execute dotnet Rnwood.Smtp**4**dev.dll to run it.' 
Typo: '... and you should execute dotnet Rnwood.Smtpdev.dll to run it.'

-----------------------

The '4' is missing.

I couldn't find a way to edit the Wiki, maybe you didn't enable it?

**Comment by rnwood** [comment]
Thanks for reporting. I have altered this.
