### ISSUE TITLE
[Feature] Option to automatically refresh list of emails

### ISSUE THREAD

**Issue by peterrow** [rnwood/smtp4dev#1549]
In the old Windows only UI the list of emails received would refresh of its own accord. In the current web UI you have to manually click the refresh button. For some reason I keep expecting the old functionality, it would be really great if an option to refresh every X seconds was available and a "Last refreshed on:  <local date/time>" message next to the list.

**Comment by rnwood** [comment]
Auto refresh is a core feature. So looks like you are seeing some issue with it working for you.

There is an indicator which shows if the connection has been established ok for the auto refresh. This area will be coloured red with an error if it has failed.

![image](https://github.com/user-attachments/assets/d9f0e58e-80cf-4da0-a1d7-96da718944a2)

What does this look like for you?
