### ISSUE TITLE
[Feature] Support retrieval of messages using POP3

### ISSUE THREAD

**Issue by TonyWoo** [rnwood/smtp4dev#155]
Hi, can we use a email client(outlook/formail/...) to retrieve the email so we can test the displaying/styling issue in different email client? Thanks.

**Comment by rnwood** [comment]
Currently you can't retrieve email directly using an external client. I 
may consider adding this feature in future, but I'd like to get all the 
basics out of the way first (PRs welcome of course!)

To achieve what you want, you can view the message in web interface and 
then press the 'Download' button (above message preview) to download the 
message as a .eml file. You can then open this in most desktop email 
clients.


------ Original Message ------
