### ISSUE TITLE
[Feature] Error simulation to reject messages

### ISSUE THREAD

**Issue by Davilink** [rnwood/smtp4dev#165]
The idea is having a way to simulate a email that cannot be sent.
We have functionality that display an error message to user if the email was unable to be sent but because we use the smtp4dev has a fake SMTP server, all email will be considered successfully sent and we cannot trigger our feature other than stopping the smtp manually when the Quality Assurance are testing this particular feature. 

It would be nice to have a way to put a email address that will trigger an unable to sent email maybe in the appsettings or by cmdline.

**Comment by rnwood** [comment]
Thanks for suggesting this. I think that this is a great idea and will consider it for the future once more basic functionality is out of the way.

**Comment by andre259** [comment]
Any further work on this idea? This would be very helpful, and it seems like it wouldn't be too hard to implement

**Comment by rnwood** [comment]
This has been implemented in PR #1377. See `MessageValidationExpression` in app settings.
