### ISSUE TITLE
[Feature] Add confirmation dialog after clicking "Clear"

### ISSUE THREAD

**Issue by UNIFY-MatthewDayne** [rnwood/smtp4dev#178]
When sharing access to stmp4dev to other users they might decide to click buttons to see what they do, currently the clear button does not ask for confirmation and can be very easy for user to accidentally remove everything.

Adding a confirmation box would help to prevent such instances occuring.

**Comment by rnwood** [comment]
Thanks for the suggestion. I agree this is a good idea. We can add a 'don't ask next time' option (remembered per user) so it's not a big deal for people that don't want this.
