### ISSUE TITLE
[Bug] "It was not possible to find any compatible framework version" error when running as a global tool on .NET Core SDK 3.1

### ISSUE THREAD

**Issue by Tobias-Gr** [rnwood/smtp4dev#211]
If .NET Core SDK 3.1 rather than 2.2 is installed start of the program terminates with:

It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '2.2.6' was not found.

But the readme says: .NET Core SDK 2.2 or greater.

**Comment by MaxDiOrio** [comment]
Hi!   Any word on this bug?  It's blocking our use, and Microsoft has recommended everyone upgrade .NET Core to 3.1 due to the 2.x branch not being an LTS branch and is no longer being updated.  Thanks!

**Comment by rnwood** [comment]
Depends on #224. Once upgraded to target 3.1 runtime the new RollForward feature in framework should ensure that the app will run on the best available runtime even if it's different major version. So when 3.2 and 5.0 come out, if one of those is available and a 3.1.x is not, then it will be used and should work provided MS don't break anything.

**Comment by rnwood** [comment]
This should now be resolved. Please note min runtime version is now 3.1..
