### ISSUE TITLE
[Feature] StartTLS Support

### ISSUE THREAD

**Issue by MaxDiOrio** [rnwood/smtp4dev#218]
It looks like you support StartTLS, but I don't see any info in the documentation about where to put the certificate, or how to enable it.  Thanks.

**Comment by rnwood** [comment]
Hi. STARTTLS is supported in [the server component we use](https://github.com/rnwood/smtpserver/). It was exposed in the v2 Windows UI, but isn't yet in the v3 web UI.

**Comment by rnwood** [comment]
This has now been implemented. STARTTLS is enabled by default with an autogenerated certificate. See the console output from startup for more details. See appsettings.json if you want to provide your own cert.
