### ISSUE TITLE
[Question] How to configure server.urls in Linux Docker Container?

### ISSUE THREAD

**Issue by eamell** [rnwood/smtp4dev#219]
I have a Linux smtp4dev container running in Kubernetes and have an ingress (NGINX) front ending it.  Unfortunately I do not see a way to set the server.urls so I can get the application to load.  Is there an environment variable I can set?

Thank you!

**Comment by eamell** [comment]
If you like I can fork and make the change and do a pull request.  It is relatively straight forward of a change.  You just need to move the entry point to a shell script that will take in the appropriate environment variables and set them in the command line.

**Comment by rnwood** [comment]
Hi @eamell. Thanks for your question. Please can you post a snippet from your nginx config so I can understand what you're trying to achieve.
