### ISSUE TITLE
[Feature] App does not run in virtual directory

### ISSUE THREAD

**Issue by tabrms** [rnwood/smtp4dev#23]
In our scenario I would like to publish website into a virtual directory. There is no option to do that. Is there a possibility to add this by detecting where the app is actually running?

**Comment by rnwood** [comment]
I presume this is when hosting in IIS? Can you let me know why this is an important use case for you as at the moment I haven't really considered this option and am targetting self-hosting.

**Comment by Opvolger** [comment]
I have the same problem. See my pull request. We have all Mocks in IIS als sub applications. So the MailServer is a sub application.

**Comment by rnwood** [comment]
This feature has now been merged.
