### ISSUE TITLE
[Question] -  I am trying to attach a pdf, when I sent it I will see the attached pdf or only the data in base64

### ISSUE THREAD

**Issue by mapeveri** [rnwood/smtp4dev#30]
Hi, I am sending an email with a pdf attached and I am receiving this message. I do not know if it's ok, because it's a test or it's definitely wrong. Thanks!

**Comment by rnwood** [comment]
Hi @mapeveri. I'm not able to reproduce this issue. Can you provide any more details or an example saved .eml file which when you send causes this?

**Comment by mapeveri** [comment]
Hi @rnwood My headers were wrong, sorry. I ask you a question, I am trying to attach a pdf, when I sent it I will see the attached pdf or only the data in base64. I'm asking you this to know if I have an error or it just works like that, since it's test mode. Thanks!

**Comment by mapeveri** [comment]
Ok, Thanks!
