### ISSUE TITLE
Connection refused on fefault web server port number (5000)

### ISSUE THREAD

**Issue by Nathan187** [rnwood/smtp4dev#33]
when navigating to localhost:5000, browser says:  

This webpage is not available

ERR_CONNECTION_REFUSED

**Comment by rnwood** [comment]
Can you provide any output from the console when you run the program please. Please also double check that if you have any personal firewall software (like Windows firewall), that you've allowed the program to listen.

**Comment by Nathan187** [comment]
I was trying to use this on a work server that was locked down pretty tight.  I didn’t mess with it too much since.  I was able to use PaperCut and it worked fine.  Thanks for replying (no sarcasm)
