### ISSUE TITLE
Option  --rooturl is not functional

### ISSUE THREAD

**Issue by lexxua** [rnwood/smtp4dev#332]
Hi, I noticed that when I`m trying to use rooturl, the application does not start at all.
Here is a small snippet what I`m getting in console:
Application startup exception: System.InvalidOperationException: The EndpointRoutingMiddleware and EndpointMiddleware must be added to the same IApplicationBuilder instance. To use Endpoint Routing with 'Map(...)', make sure to call 'IApplicationBuilder.UseRouting' before 'IApplicationBuilder.UseEndpoints' for each branch of the middleware pipeline.
 Please find a full log using following URL:
https://gist.githubusercontent.com/lexxua/ea9d4a12d13700ffbc744da9bfbedda8/raw/cc6d0177e9cd6af33c03309916b1c8affaea3538/Trace
An operating system is win10pro.

**Comment by Piedone** [comment]
Rooturl will only accept simple strings like "localhost", optionally with a port like "localhost:123". I'm not sure what it's supposed to do though since e.g. using "localhost:123" it won't actually run the web UI under http://localhost:123; for that you have to use `--urls`.

**Comment by lexxua** [comment]
Hi @Piedone , thanks for the comment. But I tried to have nginx in front of smtp4dev, like it described here:
https://www.gitmemory.com/issue/rnwood/smtp4dev/160/510045773

**Comment by rnwood** [comment]
Please note that the option has been renamed to `--basepath` or `ServerSettings` > `BasePath` to make this clearer that only a `/path` is expected.

If smtp4dev is behind a reverse proxy, and you want to present the app at something other than `/`, you need to set this option for smtp4dev to tell it the path it should respond at. You then will not need any URL rewriting etc at the reverse proxy.

**Comment by lexxua** [comment]
Hi, @rnwood thanks for the fix. Now all works like a charm!

**Comment by bberenberg** [comment]
@rnwood I assume this has been included in the docker builds? Any chance we could get the base path to be configureable via an environment variable?

**Comment by rnwood** [comment]
Hi. Yes this should be in latest Docker builds too.

See here for some recently added docs of the env vars applicable to Docker:
https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml

and here for info on configuration generally:
https://github.com/rnwood/smtp4dev/wiki/Configuration

Let me know if you have any issues.

**Comment by bberenberg** [comment]
You da best! I missed the compose update. Everything working in 3 mins of work.

**Comment by k4kratik** [comment]
Hi @bberenberg 
I think I am too late to the party but I was also facing the similar issue while using smtp4dev with nginx reverse proxy.

Then I used following config block and it worked like charm for me : 

```
    location /smtp4dev  {
        proxy_pass http://localhost:3000;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 86400;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
```

Hope this helps someone in future!!!
