### ISSUE TITLE
Add docker-compose file to smtp4dev

### ISSUE THREAD

**Issue by isacmoura** [rnwood/smtp4dev#344]
We are using smtp4dev to test a smtp service locally and I added this to a docker-compose file to smtp4dev be runned with other containers we use.

I think the official repository could have a docker-compose file to help inexperienced developers who wants to use smtp4dev as a container app. If you think is a good idea, I can make a PR with this.

**Comment by eclisia** [comment]
Dear,
I try the same but I've got error with "Unknow blob" (I've juste written an issue).
Is it possible to share your compose file ?
Do you have already faced the same issue ?
Best regards

**Comment by rnwood** [comment]
Added here: [https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml](https://github.com/rnwood/smtp4dev/blob/master/docker-compose.yml)
