### ISSUE TITLE
Web page just shows smtp4dev logo and "Loading..."

### ISSUE THREAD

**Issue by TrevorWesterdahl** [rnwood/smtp4dev#353]
I installed Rnwood.Smtp4dev-win-x64-3.1.0-ci2020041702 on a Windows 2012 R2 server and ran the command to run it as a service. SMTP files do seem to be processed, but the web page on port 5000 just shows the logo a stays in a state of "Loading..."

Any ideas on how to fix this? 

I am trying to use this in an on-prem virtual lab to test application notifications.

**Comment by rnwood** [comment]
Hi Trevor

What browser and what version of the browser?
You'll need to use a more modern browser than the IE11 which is built 
into the OS. Normally you should get a message to that effect if you try 
use a browser which is too ancient.

Thanks
Rob

------ Original Message ------
