### ISSUE TITLE
Recommended way of allowing functional SSL/TLS

### ISSUE THREAD

**Issue by ronnyek** [rnwood/smtp4dev#374]
I know on start, I get a message about a cert being created and tells me I need to trust it. I'm trying to connect with mailkit and getting this:

```
MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.

The SSL certificate presented by the server is not trusted by the system for one or more of the following reasons:
1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. The certificate presented by the server is expired or invalid.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.
```

I've installed that cert to personal in both local user and local machine as well as trying to install a few other places, and never been able to better my situation except disabling ssl/tls checks.

**Comment by ronnyek** [comment]
I was just hoping someone could provide some insight about where and how we could install this cert with trust to make it work.

**Comment by rnwood** [comment]
Hi @ronnyek. Make sure you put the cert into the 'Trusted Root Certification Authorities' store, not the default 'Personal' store.

**Comment by ronnyek** [comment]
MailKit is seeing this. I'm not sure if I need to reboot, or completely restart apps that are trying to send mail to smtp4dev or what.

```
See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#InvalidSslCertificate for possible solutions.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090331): The client and server cannot communicate, because they do not possess a common algorithm.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
```

**Comment by giansalex** [comment]
> Hi @ronnyek. Make sure you put the cert into the 'Trusted Root Certification Authorities' store, not the default 'Personal' store.

Yes, it works

**Comment by regis-ranniere** [comment]
I'm having a similar issue...
I'm running a smtp4dev on docker and when I try send a e-mail i'm getting this exception: 

```MailKit.Security.SslHandshakeException: 'An error occurred while attempting to establish an SSL or TLS connection.

This usually means that the SSL certificate presented by the server is not trusted by the system for one or more of
the following reasons:

1. The server is using a self-signed certificate which cannot be verified.
2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.
3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.
4. The certificate presented by the server is expired or invalid.

It is also possible that the set of SSL/TLS protocols supported by the client and server do not match.

See https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.
'
```
My docker is running on linux... I don't know if is this the problem...

How can I configure?

**Comment by rnwood** [comment]
@regis-ranniere The simplest option if your client doesn't require TLS is to download the newest version of smtp4dev. TLS is disabled by default in builds from today. (I misjuged the default configuration - making this enabled by default - but people need to take manual steps to make it work with some clients, so it was a poor default.)

If you do need TLS, make sure to download the latest version also. This is because there was a bug (#330) not enabling TLS1.2 which breaks some clients. Since TLS is now disabled by default, please see the instructions on startup about enabling it.

**Comment by rnwood** [comment]
Closing this issue for now.
