### ISSUE TITLE
[Bug] Sizing wrong when receiving while on tab sessions

### ISSUE THREAD

**Issue by joachimcarrein** [rnwood/smtp4dev#40]
If you are on the sessions tab and a mail is received, when you return to the messages, the subject with is compressed and not using to available width. Restores after full refresh

**Comment by joachimcarrein** [comment]
Just tested on the latest build, but was unable to get the wrong behavior.

**Comment by rnwood** [comment]
Thanks for checking.

**Comment by rnwood** [comment]
Thanks for checking.
