### ISSUE TITLE
Inspecting received messages programmatically

### ISSUE THREAD

**Issue by reponemec** [rnwood/smtp4dev#426]
Can I inspect received messages programmatically? 
If not, can you recommend me more appropriate dummy lightweight SMTP server on which it is possible? I never need to resend received messages to real smtp server.

**Comment by rnwood** [comment]
smtp4dev currently doesn't have a documented API
You can use the library which smtp4dev uses instead - https://github.com/rnwood/smtpserver/

See https://github.com/rnwood/smtpserver/blob/master/Rnwood.SmtpServer.Tests/ClientTests.cs for example of how to use. You'll need to use a MIME parser like MimeKit if you want to parse the received messages and check/retrieve any contents.
