### ISSUE TITLE
Message bodies aren't shown in Edge

### ISSUE THREAD

**Issue by ericwj** [rnwood/smtp4dev#45]
The *View* tab appears to be lame in Edge. Nothing is displayed. Neither HTML nor plain text bodies.

The *Parts* tab shows the raw content just fine.

Running the same site in Firefox, all appears to be OK.

In the screenshot, left is Edge on Windows 10.0.17134, right is latest Firefox.
![image](https://user-images.githubusercontent.com/9473119/40134440-b7c2406a-5942-11e8-803a-9db5302f90de.png)

**Comment by rnwood** [comment]
This appears to be because of lack of support for the iframe srcdoc attribute:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12375527/

**Comment by ericwj** [comment]
Can it be fixed? Outlook.com doesn't have this problem.
