### ISSUE TITLE
Chrome won't let me download binaries Blocking them

### ISSUE THREAD

**Issue by fahadash** [rnwood/smtp4dev#47]
Chrome after downloading MSI or zip binaries blocks them as malicious.

**Comment by alexpilon666** [comment]
@fahadash Are you sure it is Chrome and not some antivirus that may be explaining this ?
Which version of Chrome are you using ? 
And can you screenshot the error message you're getting ?

I've just tried downloading all the available downloads from the latest 2.0.10 version, using the latest Chrome build (68.0.3440.106), and I've had no issue.
I also enabled some security settings that may have been enabled on your end, namely "Automatically end some system information and page content tom Google to help detect dangerous apps and sites" and "Protect you and your device from dangerous sites", and it still works.

**Comment by fahadash** [comment]
I found out that Chrome no longer blocks the downloaded file. Earlier the whole tab in the bottom showing the file being downloaded had turned red and there was no way for me to override that and get the file anyway.
