### ISSUE TITLE
[Bug] SignalR hub connection not resolving BasePath

### ISSUE THREAD

**Issue by AndreasAmMueller** [rnwood/smtp4dev#487]
If you define a `ServerOption:BasePath`, the setting is used for the ASP.NET part but resolving the HubConnection the part is missing. See screenshots.

Browser:    
![grafik](https://user-images.githubusercontent.com/2407095/94203338-831ac600-febf-11ea-838b-0d66774a4ce4.png)

docker-compose.yml:    
![grafik](https://user-images.githubusercontent.com/2407095/94203403-a0e82b00-febf-11ea-819f-75c0e1b3f924.png)

NginX settings:    
![grafik](https://user-images.githubusercontent.com/2407095/94203421-aba2c000-febf-11ea-86b1-648deb163c56.png)

**Comment by rnwood** [comment]
Thanks for reporting. There's an E2E test to protect against breaking this again, but unfortunately it was returning a false positive (bad test :( ).

**Comment by rnwood** [comment]
Regression and tests fixed.
