### ISSUE TITLE
Messages sent to stderr during successful startup

### ISSUE THREAD

**Issue by Piedone** [rnwood/smtp4dev#493]
During a successful startup the process will write to stderr thrice in between messages to stdout:

1. An empty string.
2. The " > For help use argument --help" message.
3. An empty string again.

I think these are a mistake and should instead be sent to STDOUT.

I'm using a command something like:

```
dotnet.exe tool run smtp4dev --db "" --smtpport 11395 --urls http://localhost:12304/
```

This is happening with 3.1.2-ci20200930101 and wasn't happening with 3.1.0-ci2020041702.

**Comment by rnwood** [comment]
Thanks for reporting. Resolved.

**Comment by Piedone** [comment]
Thank you!
