### ISSUE TITLE
[Feature] pull from docker image

### ISSUE THREAD

**Issue by zorkind** [rnwood/smtp4dev#51]
Is there a docker image for this? it would make everything very much easier if there was one.

**Comment by tomuky2k** [comment]
This is why I just came here, I've used the Windows app for several years for testing email programs but it's now the only thing I need to install .NET 2.0/3.5 for and I'd rather not, so was hoping for a docker image. Obviously as the new version (3) isn't released yet there won't be one but expect it wouldn't be too difficult in the future.

**Comment by rnwood** [comment]
Thanks to contributor @Opvolger, this is now available on Docker hub as rnwood/smtp4dev.  The readme has been updated to show how to use. Please feel free to feedback any issues or suggestions to improve this.
