### ISSUE TITLE
[Feature] Added webui port to appsettings.json

### ISSUE THREAD

**Issue by Bootta11** [rnwood/smtp4dev#540]
I have problem with overlapping port on smtp4dev and other app, please add webui port to appsettings.json config so it can be changed from predefined 5000.

**Comment by andy250** [comment]
You can set custom port when starting the app. I have set it in the {PathToExe} when installing windows service:

C:\your\path\Rnwood.Smtp4dev.exe --service --server.urls "http://0.0.0.0:5001/"

**Comment by fjakop** [comment]
I totally agree. We are abou tot run smtp4dev in an OpenShift cluster whic does not allow root containers, so we cannot use port 80 for Kestrel and we do not intend to change the Dockerfile as well.

We can set ports for smtp and imap in the env vars like

            - name: ServerOptions__Port
              value: '1025'
            - name: ServerOptions__ImapPort
              value: '1143'

but it seems there's no option for http port.

**Comment by rnwood** [comment]
This has been implemented in PR #1462.

Please see the settings file (and existing `--urls` command line option) for info.
