### ISSUE TITLE
Sort Order in Web Interface is changing from itself

### ISSUE THREAD

**Issue by DrunkenHusky** [rnwood/smtp4dev#59]
Hi Guys 

I have the problem, that sometimes the list is sorted descending and otherwise it is sorted ascending (everytime it's the column "Received" which is sorted). I have no clue, how a user can change that or how I can configure that. 

The problem is now, that I would like to change the sort order and define a default but I don't know how to do that or is it a bug?

I mean this list:
![image](https://user-images.githubusercontent.com/11538622/46091691-9d781700-c1b3-11e8-8213-273c84111ded.png)

Thanks
Victor

**Comment by DrunkenHusky** [comment]
Is this maybe related to my reported issue?
https://github.com/rnwood/smtp4dev/pull/52/files

**Comment by rnwood** [comment]
#52 has now been merged and this issue should be resolved.

**Comment by DrunkenHusky** [comment]
Awesome, thanks! Update already in Progress 👍
