### ISSUE TITLE
[Feature] mark Mails in the UI received by StartTLS

### ISSUE THREAD

**Issue by flexguse** [rnwood/smtp4dev#596]
First of all: thanks for your work! I used smtp4dev a couple of yeas ago and today I found it can be used in Docker and supports StartTLS - great!

I was able to get smpt4dev up and running in Kubernetes using my own SSL Certificate, a client using TLS is able to send emails.

Unfortunately in the UI there is no possibility to check if the email really was sent using TLS. As far I know this information normally is included in the email header information (received by ... using TLS ...).

Currently I'm not able to verify my implementation used TLS in the UI. Did I miss something or is this feature missing?

**Comment by rnwood** [comment]
Hi. You are right; This feature is not currently exposed in the UI. The underlying SMTP library does record this in the object model so it should just be a case of storing this and displaying in UI.

Keeping this ticket open as a feature request.

**Comment by jafin** [comment]
I had a look into the headers when I configured StartTLS, I could not see the information exposed in the header collection.  I did see the state of the secure connection is available, so I exposed that to the UI, does that help?

**Comment by rnwood** [comment]
Thanks to @jafin this feature has now been implemented.
