### ISSUE TITLE
View message

### ISSUE THREAD

**Issue by rnwood** [rnwood/smtp4dev#6]

**Comment by seansparkman** [comment]
Is this not implemented or not working?

**Comment by rnwood** [comment]
Not yet fully implemented. See v2.x @ https://smtp4dev.codeplex.com/ for Windows version with this working. V3.x hosted here on github will be a major re-write to web UI so WIP.

**Comment by seansparkman** [comment]
I have looked at it.  It crashes when I send it an email on Windows 10.  I might look at sending some pull requests your way when things slow.

**Comment by Opvolger** [comment]
I have resolved this to update the following NuGet packages:
HtmlAgilityPack -> 16.17
Microsoft.AspNetCore.All -> 2.0.5
MimeKit -> 1.22.0
