### ISSUE TITLE
Port settings as a parameter

### ISSUE THREAD

**Issue by pcrosthwaite** [rnwood/smtp4dev#61]
Hi,

Just like you have --server.urls as a commandline parameter, can you allow for the server port to be specified as well?

When running multiple test environments, to separate the emails easily, its best to run smtp4dev multiple times, listening on different ports. 

Being able to specify the port when running the windows exe, would allow for a simple windows service configuration.

thanks

**Comment by rnwood** [comment]
Thanks for your suggestion. This has been implemented and added to the readme. Add ``--smtpport 26`` to your command line.args.
