### ISSUE TITLE
TLS Mode 

### ISSUE THREAD

**Issue by cdub50** [rnwood/smtp4dev#659]
On main and 3.1.2 I am trying to start the container with StartTLS=On using a self signed cert with value of "" but when container is started it shows none for TLS and when I try to send a mail with TLS it throws an error command unrecognized. What is the proper way to enable TLS with a self signed cert?

**Comment by rnwood** [comment]
The correct value to use for tlsmode is StartTLS
The value StartTLS=On is not valid, but I can see how the docs have lead you to believe this. I will update the docs to make clearer.
________________________________
From: cdub50 ***@***.***>
Sent: Tuesday, March 16, 2021 8:44:21 PM
To: rnwood/smtp4dev ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rnwood/smtp4dev] TLS Mode (#659)


On main and 3.1.2 I am trying to start the container with StartTLS=On but when container is started it shows none for TLS and when I try to send a mail with TLS it throws an error command unrecognized. What is the proper way to enable TLS with a self signed cert?

**Comment by cdub50** [comment]
I tried to set like this in the docker-compose.yml - ServerOptions__StartTls but still seeing TLS show none when container is started

**Comment by rnwood** [comment]
The correct environment setting should be
ServerOptions__TlsMode=StartTls
________________________________

**Comment by cdub50** [comment]
thank you!

**Comment by cdub50** [comment]
one last thing how do I specify an auto generated self signed cert I tried using 

- ServerOptions__TlsCertificate=""

but I see this error on start

smtp4dev_1  | The SMTP server failed to start: Interop+Crypto+OpenSslCryptographicException: error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error
smtp4dev_1  |    at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromBlob(Byte[] rawData, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
smtp4dev_1  |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
smtp4dev_1  |    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
smtp4dev_1  |    at Rnwood.Smtp4dev.Server.Smtp4devServer.GetTlsCertificate() in /app/Rnwood.Smtp4dev/Server/Smtp4devServer.cs:line 106
smtp4dev_1  |    at Rnwood.Smtp4dev.Server.Smtp4devServer.CreateSmtpServer() in /app/Rnwood.Smtp4dev/Server/Smtp4devServer.cs:line 67
smtp4dev_1  |    at Rnwood.Smtp4dev.Server.Smtp4devServer.TryStart() in /app/Rnwood.Smtp4dev/Server/Smtp4devServer.cs:line 435

**Comment by rnwood** [comment]
Comment that out. The default if not specified is to use a self signed cert.
________________________________

**Comment by cdub50** [comment]
ok thanks again for the help much appreciated!

**Comment by cdub50** [comment]
Closing this issue but Docs should be modified to make it more clear on how to add TLS and self signed cert so others dont run into the same issue.
