### ISSUE TITLE
[Bug] Header view keeps being pushed aside

### ISSUE THREAD

**Issue by joachimcarrein** [rnwood/smtp4dev#68]
When I click an email and select Headers, the divider starts to shift right and doesn't stop. until it is off screen (and even then still appears to go on)

smtp4dev is executed as service, on http://0.0.0.0:80
web interface is accessed from another machine in firefox, also tested in chrome

![video_2018-10-30_134715](https://user-images.githubusercontent.com/3807876/47719230-ce33ec00-dc4a-11e8-9c10-d463f56d7386.gif)

**Comment by RCatersels** [comment]
Yes, I have this also.

**Comment by edtorba** [comment]
Same on Win 10, Chrome 70.0.3538.110

**Comment by rnwood** [comment]
I can confirm that I can reproduce this. I've done some experimentation and It appears to be an issue with the elementui (a UI toolkit the project uses) table control when there are two table controls across the width of page in a flex layout, and where both the tables have a column set to autosize.

I have committed a temporary workaround which is simply to give one of the columns a fixed width. I will look into a better solution.
