### ISSUE TITLE
Unable to bind SMTP port if Oracle VirtualBox is installed

### ISSUE THREAD

**Issue by aheTRe** [rnwood/smtp4dev#700]
On Windows 10, when Oracles VirtualBox is installed the startup will fail with an error message that the socket bind failed for the SMTP port, changing the port in the config did not fix the issue. The IMAP and HTTP port(5000) work normal.
By deinstalling VirtualBox it somehow worked again, but i would like to use both tools.

**Comment by rnwood** [comment]
Closing stale issue. There's no indicating this is an smtp4dev issue. Most likely VirtualBox or something on one of the guest VMs is hogging the port or preventing binding to it.
