### ISSUE TITLE
Cannot set hostname for certificate through appsettings.json, but can set through --hostname

### ISSUE THREAD

**Issue by TolikKrymov** [rnwood/smtp4dev#724]

**Comment by jafin** [comment]
Hi @TolikKrymov,

Check it isn't being overridden via the config in user profile (windows)
`C:\Users\<username>\AppData\Roaming\smtp4dev\appsettings.json`

If I recall the app applies the config in the apps runtime folder, then the userprofile config, then the command line (in that order).
