### ISSUE TITLE
Feature Request: Mark Emails that are relayed

### ISSUE THREAD

**Issue by marcohald** [rnwood/smtp4dev#774]
It would be great to have Icon on a Mail in the Web interface if it was relayed.
The only other way I know to check is in the Logs

**Comment by jafin** [comment]
@marcohald  I've put in a PR for this.

Would this be a suitable option?
![image](https://user-images.githubusercontent.com/127927/128617187-88805aea-eab9-4e5d-8860-ad0e2bf6ea54.png)

**Comment by rnwood** [comment]
Thanks to @jafin again, this is now available in the latest pre release version.
