### ISSUE TITLE
Message search functionality no longer working in latest release 3.1.3.2

### ISSUE THREAD

**Issue by jorlowski6** [rnwood/smtp4dev#806]
I recently upgraded my Windows 64 bit installation of smtp4dev to version 3.1.3.2 using the binary standalone installation Rnwood.Smtp4dev-win-x64 and the message search functionality in the UI is now broken.  With my previous release, 3.1.1, the search functionality worked awesome but I needed to upgrade for the bug fix #462 to fix the relay for multiple recipients.  I also tried the release that #462 was fixed on for version 3.1.2 and experience the same issue.

When entering a value into the search box, I get the error message "Cannot read property 'localeIndexOf' of null" with the following error in the console:

Uncaught TypeError: Cannot read property 'localeIndexOf' of null
    at o.searchTermPredicate (messagelist.vue:253)
    at messagelist.vue:231
    at Array.filter (<anonymous>)
    at o.updateFilteredMessages (messagelist.vue:231)
    at index.esm.js:1

It seems to be this code from messagelist.vue that is producing the error:

  private searchTermPredicate(m: MessageSummary) {
    return !this.searchTerm ||
        m.subject.localeIndexOf(this.searchTerm, undefined, {
          sensitivity: "base"
        }) != -1 ||
        m.to.localeIndexOf(this.searchTerm, undefined, {
          sensitivity: "base"
        }) != -1 ||
        m.from.localeIndexOf(this.searchTerm, undefined, {
          sensitivity: "base"
        }) != -1;
  }

I compared all of the files in the release and I seem to have everything.  Any ideas on why this functionality is now broken in the latest releases?

**Comment by jafin** [comment]
@jorlowski6  I downloaded 3.1.3.2 and it appears to work fine (Windows/64)   I tried in Chrome 92 and Edge Chromium with success.  I found an old PC with IE11, it fails to load the app on the loading screen.

What browser and OS are you running?

**Comment by jorlowski6** [comment]
I am experiencing this issue using Windows 10 with Edge Chromium Version 92.0.902.55 as well as Chrome Version 91.0.4472.164.

**Comment by jafin** [comment]
I should of read the error closely, no subject line emails will throw an exception.

**Comment by jorlowski6** [comment]
@jafin that was the issue.  I deleted all of the emails that did not have a subject line and the search functionality is working.  I do think maybe this issue should be explored at some point but since we shouldn't have any emails from our system without a subject I am going to close this issue.
