### ISSUE TITLE
foreign key mismatch - "MessageRelays" referencing "Messages"

### ISSUE THREAD

**Issue by atziasios** [rnwood/smtp4dev#861]
Thanks for this great tool!

When I try to delete a message, it fails with status code 500 and it produces this "foreign key mismatch" error. Could you look into it?

I have the latest pre-release installed: 3.1.3-ci20210824104. I have tried by deleting the db and trying again, but the error stays the same.

Attaching the error.

Thanks,
Fanis

[error-ci20210824104.txt](https://github.com/rnwood/smtp4dev/files/7065895/error-ci20210824104.txt)

**Comment by jafin** [comment]
@atziasios , I was able to recreate a bug on a fresh database.  I believe I had a local db that wasn't in sync with the migration scripts, therefore didn't see the error before.  I've raised a PR that I believe will fix this.
