### ISSUE TITLE
Minor documentation errors

### ISSUE THREAD

**Issue by olivier65** [rnwood/smtp4dev#901]
On the Configuration page
1) "You can find the configuration file at <installlocation>\appsettings.json." The installation directory (if using `dotnet install`) is `%USERPROFILE%\.dotnet\tools` and there is no such file there.
2) The listing of command line options at the bottom is missing `--service`.

**Comment by jafin** [comment]
@olivier65 Where are you seeing `--service` used as a parameter?

In the docs, it talks about using `sc.exe` or powershell with `--service` but the smtp4dev executable doesn't appear to have a `--service` option?

```
How to run smtp4dev as a Windows service
Download one the Windows standalone versions which is applicable for your OS/architecture.

Install service in PowerShell
New-Service -Name Smtp4dev -BinaryPathName "{PathToExe} --service"
Install service in Cmd or PowerShell
sc.exe create Smtp4dev binPath= "{PathToExe} --service"
```

**Comment by craigs100** [comment]
Sorry but this section makes no sense to a Linux Mint user:-

"You can find the configuration file at <installlocation>\appsettings.json. This file is included in every release and so may be overwritten when you update. To avoid this, create a configuration file at {AppData}/smtp4dev/appsettings.json (see below) and make your customisations there."

There are appsettings.json files at :-
/home/{user}/.dotnet/tools/.store/rnwood.smtp4dev/3.1.3.2/rnwood.smtp4dev/3.1.3.2
/home/{user}/.dotnet/tools/.store/rnwood.smtp4dev/3.1.3.2/rnwood.smtp4dev/3.1.3.2/content
/home/{user}/.dotnet/tools/.store/rnwood.smtp4dev/3.1.3.2/rnwood.smtp4dev/3.1.3.2/contentFiles/any/netcoreapp3.1
/home/{user}/.dotnet/tools/.store/rnwood.smtp4dev/3.1.3.2/rnwood.smtp4dev/3.1.3.2/tools/netcoreapp3.1/any

I don't see an "AppData" directory anywhere. 

Please advise as I'd love to use this tool.

Rgds.

**Comment by jafin** [comment]
I don't have a Linux env running, according to this page; https://developers.redhat.com/blog/2018/11/07/dotnet-special-folder-api-linux#

`AppData` maps to:

![image](https://user-images.githubusercontent.com/127927/145124364-416fd5fb-6b58-42de-973a-37bcfe262716.png)

**Comment by craigs100** [comment]
Thanks for that. I placed it in /home/{user}/.config/smtp4dev/ alongside the database.db.

One more thing though, there's no info about how to access the UI. It's no use without. I'm developing web sites using dotnet core 5 using Rider on Linux Mint. I can run smtp4dev from terminal but then what? Does an interface just pop up when an email is received, do we have to set something up as a web interface (which I'm happy to do if I know what's happening)?

Please advise, or better still, update the docs.

Rgds

**Comment by jafin** [comment]
@craigs100  

The default configuration will have the website interface running on `http://localhost:5000`

https://github.com/rnwood/smtp4dev/wiki/Installation
`
Open your browser at http://localhost:5000. To run the web server on a different port or make it listen on interfaces other than loopback, add the command line arg --urls "http://0.0.0.0:5001/" when starting the executable.
`

It should also provide the listening port on app startup
```
Now listening on: http://0.0.0.0:5250
```

**Comment by craigs100** [comment]
Thanks,  I can't get it to start I'm afraid so probably bailing out. But FYI, I get this (Linux Mint 20.1 DOTNET 5.0):-

craig@TIUCL-XPS15:~$ smtp4dev
smtp4dev version 3.1.3.2
https://github.com/rnwood/smtp4dev

.NET Core runtime version: 3.1.21


 > For help use argument --help

Using Sqlite database at /home/craig/.config/smtp4dev/database.db
> clientapp@1.0.0 serve
> vue-cli-service serve "--port" "8123"
sh: 1: vue-cli-service: not found

TLS mode: None

The SMTP server failed to start: System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at Rnwood.SmtpServer.SmtpServer.Start()
   at Rnwood.Smtp4dev.Server.Smtp4devServer.TryStart() in /home/vsts/work/1/s/Rnwood.Smtp4dev/Server/Smtp4devServer.cs:line 437
IMAP Server listening on port 143
Hosting environment: Development
Content root path: /home/craig/.dotnet/tools/.store/rnwood.smtp4dev/3.1.3.2/rnwood.smtp4dev/3.1.3.2/tools/netcoreapp3.1/any
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.

Rgds.

**Comment by jafin** [comment]
@craigs100  apologies, as mentioned I'm not in a position to assist with linux configs. From what you posted, it appears the SMTP port failed to bind, possibly because you already have an existing daemon configured on that port. 
You can configure the smtp4dev port in the appsettings.json  under section to another port (ie 2525) that may get you going.

```json
{"ServerOptions": {
 "Port": 25
}
```
https://github.com/rnwood/smtp4dev/wiki/Configuration

**Comment by aaronamm** [comment]
@craigs100 I am not sure if you have solved this issue. If so, could you please share it to us.
I have tested with the following command to start smtp4dev server but still got an error.
command:
```sh
$ smtp4dev --urls "https://0.0.0.0:8080/" --smtpport 2525
```
error message:
```sh
The IMAP server failed to start: System.Net.Sockets.SocketException (13): Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at LumiSoft.Net.TCP.TCP_Server`1.StartListen()
```

FYI, I don't have any issues with smtp4dev Docker and I can use it with an application that runs under WSL2.
```sh
docker run --rm -it -p 3000:80 -p 2525:25 rnwood/smtp4dev
```

CC @jafin.

**Comment by craigs100** [comment]
@aaronamm I'm afraid I gave up and now use [mailtrap](https://mailtrap.io/) instead. It just works.  Good luck.

**Comment by kvydm01** [comment]
There's this setting for IMAP port that needs to be changed to get rid of The IMAP server failed to start: Permission denied problem:
"ImapPort": 143

**Comment by MarkusGnigler** [comment]
@craigs100

Don't make your life hard and install such a small tool. Use docker instead  ;)

Bash
```bash
docker run -it --rm \
    --publish 3030:80 \
    --publish 25:25 \
    --publish 143:143 \
    --name smtp4dev \
    --env ServerOptions__TlsMode=StartTls \
    rnwood/smtp4dev
```

Powershell
```ps1
docker run -it --rm `
    --publish 3030:80 `
    --publish 25:25 `
    --publish 143:143 `
    --name smtp4dev `
    --env ServerOptions__TlsMode=StartTls `
    rnwood/smtp4dev
```

**Comment by craigs100** [comment]
I haven't even thought about using this tool since I raised the issue. Time and tech has moved on. I just use a mailtrap.io account for test purposes now. Never fails.  If you think transferring to Docker is such a small thing, I'd think again if I were you!  Good luck ;)

**Comment by rnwood** [comment]
@craigs100 Thanks for the feedback. I appreciate that it was/is much harder to get smtp4dev running than the $16/month SAAS mailtrap service which you can just sign up for! I'd love to allow a one click deployment to a cloud provider right from the github readme.

One of the key things people in this thread didn't understand was that on Linux, ports < 1000 cannot be used by programs not running as root. So I've logged a ticket to improve that in the docs plus what happens if smtp4dev is started and it cannot bind (it's now just a case of clicking settings and changing the port number or running as root).

The other is the confusion about where settings load from and lack of awareness that all the basic settings can be done from the settings dialog in the UI. We will also take actions here also.

**Comment by craigs100** [comment]
Thanks. All good. MailTrap is actually free btw, or at least I only use the free tier for testing SMTP transport from code.

Good luck

**Comment by valcands** [comment]
Hello! I run it on Win10x64 and smtp works fine. But IMAP makes only connection and didn't fire an event for my app when new mail came to mailbox. Thanks for any comments on it!
