### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by olivier65** [rnwood/smtp4dev#902]
Restarting smtp4dev 3.1.3.2 after creating an appsettings.json file fails with:
```
System.Text.Json.JsonReaderException: ':' is invalid after a single JSON value. Expected end of data. LineNumber: 8
```
That is with the default file, exactly as on the configuration page of the wiki (hence line 8) but it always fails at the first non-comment line. The beginning of the `dotnet --info` output is:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.19
  Commit:  aae002469c
```

**Comment by jafin** [comment]
@olivier65 ,

I downloaded 3.1.3.2 to an empty folder and ran the executable
Everything started up ok.
There was no need to create an appsettings.json, it should already exist.

The section in the wiki I think you are referring to is only PART of the config, to replace the existing ServerOptions properties.  
If you could recommend an edit that would make that clearer?
