### ISSUE TITLE
Add Paging

### ISSUE THREAD

**Issue by bsulliva** [rnwood/smtp4dev#906]
We have thousands of emails over a long period of time and smtp4dev is painfully slow and almost unusable. Many times the page becomes unresponsive. Any way we could add paging to the UI so we don't have to try to load thousands of emails?

**Comment by jafin** [comment]
I've got an example branch with paging for messages, one issue it does highlight is that the search is client-side, therefore when you search on paged results, it will only match the paged data, not the entire data set.

So I think the next step would be to make a change to push search to be a backend request, which returns paged + filtered results.

![image](https://user-images.githubusercontent.com/127927/134825257-3a09a116-f703-4bf3-90e2-b9bbfd38621a.png)

**Comment by bsulliva** [comment]
This is awesome, it's nice to have the paging feature. Good call out on the searching feature. I haven't used it to much, so not sure how critical it is or how hard to implement. I would think the sorting feature would be able to get around it until the server side search is added.

**Comment by jafin** [comment]
@bsulliva , ok if this is useful without the search, I'll organisation to wrap up the code I have and submit a PR.
