### ISSUE TITLE
Add notification api to web interface

### ISSUE THREAD

**Issue by redtopia** [rnwood/smtp4dev#93]
I've been using smtp4dev for years in Win7, and have recently setup version 3 for a new computer. I realize this is work in progress, and while I don't expect everything to be perfect, a lack of any notification that email has arrived is a bit of a problem for me. Would it be possible to quickly add some code to send notifications to the browser using the [Notifications API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API)?

Thanks for all your work on this project!

**Comment by rnwood** [comment]
Thanks for your suggestion. 
This has been implemented and is available in the latest builds.
