### ISSUE TITLE
Size limit of database.db

### ISSUE THREAD

**Issue by arrthy** [rnwood/smtp4dev#935]
My smtp4dev receives large amount of emails and the UI doesn't display the messages/seesions after the database.db reaches over a certain limit. I have set NumberOfMessagesToKeep and NumberOfSessionsToKeep as 10000. Is there any limit to these parameters and the database size?
I get the below error when this happens.
![image](https://user-images.githubusercontent.com/41236583/137116195-f3c36571-14d8-43ed-9142-3ed356893fb8.png)

When I clear the database.db, it works again but of course I lose all the message.

**Comment by arrthy** [comment]
@jafin Nope, the mails are definitely not close to 10000. 
I use the latestSmtp4dev version 3.1.3.2

**Comment by arrthy** [comment]
It is partially broken again now. The messages are being displayed but the session data are having trouble.

![image](https://user-images.githubusercontent.com/41236583/137306507-7d90cd95-1549-44cc-964d-25b5c83bfaaa.png)

**Comment by jafin** [comment]
@arrthy - If your db has > 8192 sessions it will error.  Either set your `NumberOfSessionsToKeep` a value less than `8192` or wait if the PR for pagination gets accepted, which should resolve the issue as well (by virtue of limiting results to the client)

**Comment by arrthy** [comment]
@jafin Understood, I will try reducing ```NumberOfSessionsToKeep``` for now.
