### ISSUE TITLE
EHLO command not returning correct responses

### ISSUE THREAD

**Issue by anthonyvdotbe** [rnwood/smtp4dev#97]
I'm having the same issue as described in #5 : the server's EHLO response contains lines like:

> 8BITMIME
SIZE

instead of:

> 250-8BITMIME
250-SIZE

**Comment by rnwood** [comment]
Thanks for reporting. This looks like a duplicate of #62. Please can you confirm which platform you're using so we can confirm that?

**Comment by anthonyvdotbe** [comment]
Yes, I'm using the Docker Linux image (sorry I forgot to mention that in the report), so this is indeed a duplicate of #62.
