### ISSUE TITLE
Extreme memory use when run as Windows service

### ISSUE THREAD

**Issue by DanielSpindler83** [rnwood/smtp4dev#979]
Configured to run as a Windows Service. 
Receiving around 1000 emails - the memory use balloons up over 3Gb and is never released.
Set Number of messages to keep as 100
Set Number of session to keep at 10
Is this expected?

**Comment by jafin** [comment]
Hi @DanielSpindler83 , which version are you running?
Some metrics from a prior patch, tested with 5000 messages app ran to about 1.2gb/ram and then got recycled. See https://github.com/rnwood/smtp4dev/pull/714

Message size payload was about 2kb.  Do you know what size your messages payload typically is?

There could definitely be something else going on, any more info you can provide would be useful.

**Comment by DanielSpindler83** [comment]
Thanks @jafin , I was indeed using an old build. I was using the April build Rnwood.Smtp4dev-win-x64-3.1.3.2.zip.
Our message size is not large, but its html with some images - so around 20-50Kb per email - no attachments.
We have batch email runs that often run between 500 -1500 emails.
I am using Windows Server 2016 on latest build\patch.
I was using a dedicated account on the Windows Service, and could confirm there was a database.db - so not running in memory.
I was seeing the app basically use all memory that was available. and never release it.

I have moved to latest build and will keep an eye on it and re-raise if still an issue.

Thanks again.
