### ISSUE TITLE
smtp4dev won't run if ASPNETCORE_ENVIRONMENT environment variable is 'Development'

### ISSUE THREAD

**Issue by christofjans** [rnwood/smtp4dev#99]
I installed smtp4dev using the dotnet tool command:

    dotnet tool install -g Rnwood.Smtp4dev --version "3.0.0-*"

Then, when I try to run it using `smtp4dev` I get reams of errors but the most important one seems to be related to `aspnet-webpack`

```
Application startup exception: System.AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
```

**Comment by rnwood** [comment]
Please can you confirm what it prints during startup:
`Hosting environment: Production`

**Comment by christofjans** [comment]
After executing the command `smtp4dev` the first few lines are:

```
smtp4dev version 3.0.0.0
https://github.com/rnwood/smtp4dev

Application startup exception: System.AggregateException: One or more errors occurred. (Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
```

I did not see the output `Hosting environment:` anywhere.

The value of the env var `ASPNETCORE_ENVIRONMENT` is indeed set to `Development` on my machine (and that's not going to change).
